apiVersion: base.scone.cloud/v1beta1
kind: SGXPlugin
metadata:
  name: sgxplugin
spec:
  autoUpdate: true
  image: "${IMAGE_REPO}/${IMAGE_PREFIX}sgx-plugin:5.9.0-rc.12-tmp"
  imagePullSecrets:
   - name: scone-operator-pull
  imagePullPolicy: Always
  namespace: scone-system
  podAnnotations:
    scone-operator/inject-pull-secret:  "true"
  ${NODESELECTORKEY}
    ${NODESELECTOR}
