apiVersion: services.scone.cloud/v1beta1
kind: CAS
metadata:
  name: "${NAME}"
  namespace: "${NAMESPACE}"
spec:
  image: "${IMAGE}"
  imagePullSecrets:
    - name: sconeapps
  service:
    type: NodePort
  imagePullPolicy: Always
  persistence:
    enabled: true
  databaseSnapshots:
    enabled: true
    interval: 24h0m0s
    persistence:
      enabled: true
  podAnnotations:
    sconeapps/inject-pull-secret:  "true"
  backup-controller:
    enabled: true
    session: "${POLICY_NAME}/register"
    image: "${IMAGE_REPO}/${IMAGE_PREFIX}backup-controller:6.0.2"
  livenessProbe:
    enabled: true
#    failureThreshold: 5
#    periodSeconds: 60
#    timeoutSeconds: 60
#    initialDelaySeconds: 30
  startupProbe:
     enabled: true
#    failureThreshold: 5
#    periodSeconds: 60
#    timeoutSeconds: 60
#    initialDelaySeconds: 30
  attestedCLIProbes: false
  networkPolicy:
    enabled: false
  nodeSelector:
    las.scontain.com/ok: "true"
