apiVersion: base.scone.cloud/v1beta1
kind: LAS
metadata:
  name: las
spec:
  autoUpdate: true
  image: "${IMAGE_REPO}/${IMAGE_PREFIX}las:6.0.2"
  imagePullSecrets:
   - name: scone-operator-pull
  imagePullPolicy: Always
  namespace: $NAMESPACE
  podAnnotations:
    scone-operator/inject-pull-secret:  "true"
  dcapKey: "${DCAP_KEY}"
